# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: home
    url: /
    weight: 1

  - name: research.
    url: research
    weight: 10

  - name: people.
    identifier: people
    url: people
    weight: 20

  - name: pi
    parent: people
    url: author/shuwen-yue
    weight: 21

  - name: group members
    parent: people
    url: people
    weight: 22

  - name: alumni
    parent: people
    url: people
    weight: 23

  - name: papers.
    url: papers
    weight: 30

  - name: news.
    url: news
    weight: 40

