# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: HOME
    url: /
    weight: 10

  - name: RESEARCH
    url: research
    weight: 20

  - name: PEOPLE
    identifier: people
    url: people
    weight: 30

  - name: PUBLICATIONS
    url: publication
    weight: 40

  - name: NEWS
    url: news
    weight: 50

